# Generated by Django 3.2.5 on 2021-07-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='time',
        ),
        migrations.AddField(
            model_name='report',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
