# Generated by Django 3.2.5 on 2021-07-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210710_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='city',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.CharField(default='NA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='zip',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
