# Generated by Django 3.2.5 on 2021-07-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210710_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='zip',
            new_name='zipcode',
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
