# Generated by Django 3.2.5 on 2021-07-26 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.CharField(max_length=2, validators=[django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='zipcode',
            field=models.CharField(max_length=5, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
